weble4/linked-house-backend

src/main/java/com/weble/linkedhouse/LinkedHouseApplication.java, src/main/java/com/weble/linkedhouse/customer/entity/Customer.java, src/main/java/com/weble/linkedhouse/customer/entity/CustomerProfile.java, src/main/java/com/weble/linkedhouse/host/entity/Host.java, src/main/java/com/weble/linkedhouse/host/entity/constant/ApproveState.java, src/main/java/com/weble/linkedhouse/host/entity/constant/LockState.java, src/main/java/com/weble/linkedhouse/house/entity/House.java, src/main/java/com/weble/linkedhouse/reservation/entity/Reservation.java
=> 코드 수정 및 호스트 엔티티 작성

src/main/java/com/weble/linkedhouse/host/entity/Host.java, src/main/java/com/weble/linkedhouse/house/entity/House.java, src/main/java/com/weble/linkedhouse/reservation/entity/CancelReservation.java
예약 취소 테이블 작성 
PR 리뷰 요청
close#24
=> 예약 취소 엔티티 테이블 작성

src/main/java/com/weble/linkedhouse/message/Message.java, src/main/java/com/weble/linkedhouse/message/constant/ReadCheck.java
- Message Entity 클래스 만들기
- EnumType 만들기
close#27
=> 메시지 도메인 관련 작성

src/main/java/com/weble/linkedhouse/review/entity/FeedbackCustomer.java
=> 게스트 리뷰 도메인 작성 완료

src/main/java/com/weble/linkedhouse/review/entity/FeedbackCustomer.java
=> 생성자 불필요한 column삭제함

build.gradle, src/main/java/com/weble/linkedhouse/customer/controller/CustomerController.java, src/main/java/com/weble/linkedhouse/customer/controller/ProfileController.java, src/main/java/com/weble/linkedhouse/customer/dtos/CustomerDto.java, src/main/java/com/weble/linkedhouse/customer/dtos/ProfileDtos.java, src/main/java/com/weble/linkedhouse/customer/dtos/request/SignupRequest.java, src/main/java/com/weble/linkedhouse/customer/dtos/response/SignupResponse.java, src/main/java/com/weble/linkedhouse/customer/entity/Customer.java, src/main/java/com/weble/linkedhouse/customer/entity/CustomerProfile.java, src/main/java/com/weble/linkedhouse/customer/entity/constant/AuthState.java, src/main/java/com/weble/linkedhouse/customer/repository/CustomerRepository.java, src/main/java/com/weble/linkedhouse/customer/repository/ProfileRepository.java, src/main/java/com/weble/linkedhouse/customer/service/CustomerService.java, src/main/java/com/weble/linkedhouse/customer/service/ProfileService.java, src/main/java/com/weble/linkedhouse/message/Message.java, src/main/resources/application.yml, src/test/resources/application.yml
- Repository , Service , Controller 작성
- Message Entity 수정
- library 추가 
- 메일 인증에 필요한 filed를 Customer Entity에 추가
close#41
=> Customer API 설계 작성

src/main/java/com/weble/linkedhouse/customer/dtos/request/SignupRequest.java, src/main/java/com/weble/linkedhouse/customer/service/CustomerService.java, src/main/java/com/weble/linkedhouse/exception/AlreadyExistEmailException.java, src/main/java/com/weble/linkedhouse/exception/InvalidSignInInformation.java, src/main/java/com/weble/linkedhouse/exception/LinkedHouseException.java, src/main/java/com/weble/linkedhouse/exception/NotExistCustomer.java, src/main/java/com/weble/linkedhouse/exception/Unauthorized.java, src/main/java/com/weble/linkedhouse/exception/controller/ExceptionControllerAdvise.java, src/main/java/com/weble/linkedhouse/exception/response/ErrorResponse.java
- Exception Controller 정의
- Custome Exception 정의
- ErrorResponse 클래스 타입 정의
- Validation 태그 @NotNull -> @NotBlank 전환. 더 확실한 검증
=> validation 추가 수정 및 Custome Exception 클래스 작성

build.gradle, src/main/java/com/weble/linkedhouse/security/jwt/JwtAuthenticationFilter.java, src/main/java/com/weble/linkedhouse/security/jwt/JwtProperties.java, src/main/java/com/weble/linkedhouse/security/jwt/JwtTokenProvider.java, src/main/java/com/weble/linkedhouse/security/jwt/token/RefreshToken.java, src/main/java/com/weble/linkedhouse/security/jwt/token/TokenDto.java
- filter
- properties
- provider 등을 만들고 있고, 아직 작업 완료가 되지 않았다.
this closed#55
=> jwt 관련 라이브러리 및 클래스 추가

src/main/java/com/weble/linkedhouse/review/repository/FeedbackCustomerRepository.java, src/main/java/com/weble/linkedhouse/review/repository/FeedbackHostRepository.java
=> 리뷰 리포지토리 작성 #52

.gitignore, src/main/java/com/weble/linkedhouse/customer/service/CustomerService.java, src/main/java/com/weble/linkedhouse/exception/JwtNullException.java, src/main/java/com/weble/linkedhouse/security/SecurityConfig.java, src/main/java/com/weble/linkedhouse/security/UserDetailsImpl.java, src/main/java/com/weble/linkedhouse/security/UserDetailsServiceImpl.java, src/main/java/com/weble/linkedhouse/security/jwt/JwtAuthenticationFilter.java, src/main/java/com/weble/linkedhouse/security/jwt/JwtReturn.java, src/main/java/com/weble/linkedhouse/security/jwt/JwtTokenProvider.java, src/main/resources/application.yml
- JWT Provider 및 UserDetailsService, UserDetailsImpl 구현.
- Security 설정 작성 완료
- SecretKey 생성 및 암호화
- gitIgnore 관련 설정
=> Security 관련 설정

src/main/java/com/weble/linkedhouse/house/dto/HouseDTO.java, src/main/java/com/weble/linkedhouse/house/entity/constant/AutoReservation.java, src/main/java/com/weble/linkedhouse/house/repository/HouseRepository.java
- JpaRepository 를 상속한 HouseRepository 구현
- HouseDTO 구현
- 열거형 AutoReservation 수정
=> House Repository 구현

build.gradle, src/main/java/com/weble/linkedhouse/customer/controller/CustomerController.java, src/main/java/com/weble/linkedhouse/customer/dtos/request/LoginRequest.java, src/main/java/com/weble/linkedhouse/customer/dtos/request/SignupRequest.java, src/main/java/com/weble/linkedhouse/customer/dtos/response/LoginResponse.java, src/main/java/com/weble/linkedhouse/customer/dtos/response/SignupResponse.java, src/main/java/com/weble/linkedhouse/customer/repository/ProfileRepository.java, src/main/java/com/weble/linkedhouse/customer/service/CustomerService.java, src/main/java/com/weble/linkedhouse/exception/AlreadyExistEmailException.java, src/main/java/com/weble/linkedhouse/exception/InvalidSignInInformation.java, src/main/java/com/weble/linkedhouse/exception/JwtNullException.java, src/main/java/com/weble/linkedhouse/exception/LinkedHouseException.java, src/main/java/com/weble/linkedhouse/exception/NotExistCustomer.java, src/main/java/com/weble/linkedhouse/exception/Unauthorized.java, src/main/java/com/weble/linkedhouse/exception/response/ErrorMessage.java, src/main/java/com/weble/linkedhouse/security/SecurityConfig.java, src/main/java/com/weble/linkedhouse/security/jwt/JwtAuthenticationFilter.java, src/main/java/com/weble/linkedhouse/security/jwt/JwtProperties.java, src/main/java/com/weble/linkedhouse/security/jwt/JwtTokenProvider.java, src/main/java/com/weble/linkedhouse/security/jwt/token/RefreshToken.java, src/main/java/com/weble/linkedhouse/security/jwt/token/RefreshTokenRepository.java, src/main/java/com/weble/linkedhouse/util/config/RedisConfig.java, src/main/resources/application.yml
- redis 이용한 refresh token 저장.
- 로그인시 Jwt Refresh Token과 access Token 발급
- redis 이용을 위한 Config 설정
- redis 라이브러리 추가 및 yml을 통한 설정
- 기존 security 수정 및 jwt 관련 패키지들 수정
=> Jwt를 이용한 가입 및 로그인 구현

src/main/java/com/weble/linkedhouse/review/controller/ReviewController.java, src/main/java/com/weble/linkedhouse/review/dtos/response/CustomerFeedbackResponse.java, src/main/java/com/weble/linkedhouse/review/dtos/response/CustomerReviewResponse.java, src/main/java/com/weble/linkedhouse/review/dtos/response/HostFeedbackResponse.java, src/main/java/com/weble/linkedhouse/review/dtos/response/HostReviewResponse.java, src/main/java/com/weble/linkedhouse/review/service/FeedbackCustomerService.java, src/main/java/com/weble/linkedhouse/review/service/FeedbackHostService.java
=> Feature/#68 review controller 코드 작성

src/main/java/com/weble/linkedhouse/config/WebSecurityConfig.java, src/main/java/com/weble/linkedhouse/exception/controller/ExceptionControllerAdvice.java, src/main/java/com/weble/linkedhouse/review/dtos/response/CustomerFeedbackResponse.java, src/main/java/com/weble/linkedhouse/review/dtos/response/CustomerReviewResponse.java, src/main/java/com/weble/linkedhouse/review/dtos/response/HostFeedbackResponse.java, src/main/java/com/weble/linkedhouse/review/service/FeedbackCustomerService.java, src/main/java/com/weble/linkedhouse/review/service/FeedbackHostService.java, src/main/java/com/weble/linkedhouse/review/web/controller/ReviewController.java, src/main/java/com/weble/linkedhouse/review/web/dtos/request/CustomerReviewRequest.java, src/main/java/com/weble/linkedhouse/review/web/dtos/request/HostReviewRequest.java, src/main/java/com/weble/linkedhouse/review/web/dtos/response/CustomerReviewResponse.java, src/main/java/com/weble/linkedhouse/review/web/dtos/response/HostReviewResponse.java
=> dto 1개 커밋 + 오타 자 수정

.github/workflows/workflow.yml, src/main/java/com/weble/linkedhouse/customer/dtos/CustomerDto.java, src/test/java/com/weble/linkedhouse/LinkedHouseApplicationTests.java, src/test/java/com/weble/linkedhouse/customer/config/TestConfig.java, src/test/java/com/weble/linkedhouse/customer/service/CustomerServiceTest.java, src/test/resources/application.yml
- customerdto id 추가
- github action 설정 파일인 workfloww yml 추가. 다만, 오류가 발견되면 언제든 수정이나 삭제 예정.
=> github action 관련 

src/main/java/com/weble/linkedhouse/customer/controller/CustomerController.java, src/main/java/com/weble/linkedhouse/customer/dtos/request/UpdateRequest.java, src/main/java/com/weble/linkedhouse/house/controller/HouseHostController.java, src/main/java/com/weble/linkedhouse/house/dto/request/UpdateHouseRequestDto.java, src/main/java/com/weble/linkedhouse/reservation/controller/ReservationController.java, src/main/java/com/weble/linkedhouse/util/UseTimeAop.java
- ReservationController에 있던 중복 @EnableMethodSecurity 삭제
- API 실행 시간 추적을 위한 TIme Aop 실 적용
- Valid 필요한 부분 추가
=> 오류 일으키는 부분 fix

src/main/java/com/weble/linkedhouse/review/controller/ReviewController.java, src/main/java/com/weble/linkedhouse/review/dtos/request/CustomerReviewRequest.java, src/main/java/com/weble/linkedhouse/review/dtos/request/HostReviewRequest.java, src/main/java/com/weble/linkedhouse/review/dtos/response/CustomerReviewResponse.java, src/main/java/com/weble/linkedhouse/review/dtos/response/HostReviewResponse.java, src/main/java/com/weble/linkedhouse/review/entity/FeedbackCustomer.java, src/main/java/com/weble/linkedhouse/review/entity/FeedbackHost.java, src/main/java/com/weble/linkedhouse/review/repository/FeedbackCustomerRepository.java, src/main/java/com/weble/linkedhouse/review/repository/FeedbackHostRepository.java, src/main/java/com/weble/linkedhouse/review/service/FeedbackCustomerService.java, src/main/java/com/weble/linkedhouse/review/service/FeedbackHostService.java
=> revert 후 review단 자료 백업

src/main/java/com/weble/linkedhouse/admin/controller/AdminController.java, src/main/java/com/weble/linkedhouse/admin/service/AdminService.java, src/main/java/com/weble/linkedhouse/notification/dtos/NoticeAll.java, src/main/java/com/weble/linkedhouse/notification/dtos/NotificationCreateRequest.java, src/main/java/com/weble/linkedhouse/notification/dtos/NotificationDto.java, src/main/java/com/weble/linkedhouse/notification/entity/Notification.java
=> notice 알림 admin단 코드 작성

src/main/java/com/weble/linkedhouse/bookmark/controller/BookMarkController.java, src/main/java/com/weble/linkedhouse/bookmark/repository/BookMarkRepository.java, src/main/java/com/weble/linkedhouse/bookmark/repository/BookMarkRepositoryImpl.java, src/main/java/com/weble/linkedhouse/bookmark/service/BookMarkService.java, src/main/java/com/weble/linkedhouse/customer/repository/DynamicRepoImpl.java, src/main/java/com/weble/linkedhouse/customer/service/CustomerService.java, src/main/java/com/weble/linkedhouse/exception/NotExistReview.java, src/main/java/com/weble/linkedhouse/exception/NotReportReview.java, src/main/java/com/weble/linkedhouse/exception/response/ErrorMessage.java, src/main/java/com/weble/linkedhouse/notification/entity/Notification.java, src/main/java/com/weble/linkedhouse/report/controller/ReportController.java, src/main/java/com/weble/linkedhouse/report/dto/CustomerReviewReportRequest.java, src/main/java/com/weble/linkedhouse/report/dto/HostReviewReportRequest.java, src/main/java/com/weble/linkedhouse/report/entity/Report.java, src/main/java/com/weble/linkedhouse/report/repository/ReportRepository.java, src/main/java/com/weble/linkedhouse/report/service/ReportService.java, src/main/java/com/weble/linkedhouse/review/controller/ReviewController.java, src/main/java/com/weble/linkedhouse/review/dtos/request/CustomerReviewRequest.java, src/main/java/com/weble/linkedhouse/review/dtos/request/HostReviewRequest.java, src/main/java/com/weble/linkedhouse/review/entity/FeedbackCustomer.java, src/main/java/com/weble/linkedhouse/review/entity/FeedbackHost.java, src/main/java/com/weble/linkedhouse/review/repository/FeedbackCustomerRepository.java, src/main/java/com/weble/linkedhouse/review/repository/FeedbackHostRepository.java, src/main/java/com/weble/linkedhouse/review/service/FeedbackCustomerService.java, src/main/java/com/weble/linkedhouse/review/service/FeedbackHostService.java, src/main/java/com/weble/linkedhouse/security/jwt/JwtAuthenticationFilter.java, src/main/java/com/weble/linkedhouse/security/jwt/JwtTokenProvider.java
- 신고 API 단 작성
- Jwt 및 Bookmark, Review 관련 코드들 리팩토링
=> 신고 API 작성 , 코드 리펙토링

src/main/java/com/weble/linkedhouse/admin/controller/AdminController.java, src/main/java/com/weble/linkedhouse/admin/service/AdminService.java, src/main/java/com/weble/linkedhouse/notification/dtos/NoticeAll.java
=> admin의 host review단 작성 완료

build.gradle, src/main/java/com/weble/linkedhouse/exception/AlreadyPayReservationException.java, src/main/java/com/weble/linkedhouse/exception/NotExistReservation.java, src/main/java/com/weble/linkedhouse/exception/response/ErrorMessage.java, src/main/java/com/weble/linkedhouse/house/dto/request/HostHouseSaveRequest.java, src/main/java/com/weble/linkedhouse/house/dto/request/UpdateHouseRequestDto.java, src/main/java/com/weble/linkedhouse/house/dto/response/HouseResponseDto.java, src/main/java/com/weble/linkedhouse/house/entity/House.java, src/main/java/com/weble/linkedhouse/house/service/HouseHostService.java, src/main/java/com/weble/linkedhouse/payment/controller/PaymentController.java, src/main/java/com/weble/linkedhouse/payment/dto/request/PaymentRequestDto.java, src/main/java/com/weble/linkedhouse/payment/dto/response/PaymentResponseDto.java, src/main/java/com/weble/linkedhouse/payment/entity/Payment.java, src/main/java/com/weble/linkedhouse/payment/repository/PaymentRepository.java, src/main/java/com/weble/linkedhouse/payment/service/PaymentService.java, src/main/java/com/weble/linkedhouse/reservation/controller/CancelReservationController.java, src/main/java/com/weble/linkedhouse/reservation/controller/ReservationController.java, src/main/java/com/weble/linkedhouse/reservation/dto/CancelReservationDTO.java, src/main/java/com/weble/linkedhouse/reservation/dto/request/CancelReservationRequest.java, src/main/java/com/weble/linkedhouse/reservation/dto/request/ReservationRequest.java, src/main/java/com/weble/linkedhouse/reservation/dto/response/ReservationResponse.java, src/main/java/com/weble/linkedhouse/reservation/entity/CancelReservation.java, src/main/java/com/weble/linkedhouse/reservation/entity/Reservation.java, src/main/java/com/weble/linkedhouse/reservation/entity/constant/PaymentState.java, src/main/java/com/weble/linkedhouse/reservation/service/CancelReservationService.java, src/main/java/com/weble/linkedhouse/reservation/service/ReservationService.java, src/main/java/com/weble/linkedhouse/review/entity/FeedbackHost.java, src/main/java/com/weble/linkedhouse/security/jwt/JwtAuthenticationFilter.java
- 에러 클레스 생성
- Entity 필요한 필드 추가
- Dto에 노출된 Entity 삭제
=> 포스트맨을 이용해 실제 API 수정

src/main/java/com/weble/linkedhouse/house/dto/request/UpdateHouseRequestDto.java, src/test/java/com/weble/linkedhouse/house/service/HouseServiceTest.java
=> fix : updateHouseTest Error

src/main/java/com/weble/linkedhouse/admin/service/AdminService.java, src/main/java/com/weble/linkedhouse/review/dtos/response/HostReviewResponse.java, src/main/java/com/weble/linkedhouse/review/repository/FeedbackHostRepository.java, src/test/java/com/weble/linkedhouse/admin/service/AdminServiceTest.java, src/test/java/com/weble/linkedhouse/customer/service/CustomerServiceTest.java
=> #117 테스트 코드 작성 완료

src/main/java/com/weble/linkedhouse/admin/controller/AdminController.java, src/main/java/com/weble/linkedhouse/admin/service/AdminService.java
전체조회, 개별조회 및 리뷰 삭제 입니다.
검토바랍니다. :)
=> Admin house조회, 삭제

src/main/java/com/weble/linkedhouse/admin/controller/AdminController.java, src/main/java/com/weble/linkedhouse/admin/service/AdminService.java, src/test/java/com/weble/linkedhouse/admin/service/AdminServiceTest.java
=> Feature/#147admin 관련 테스트, 오타수정

build.gradle, src/main/java/com/weble/linkedhouse/customer/CustomerDeleteScheduled.java, src/main/java/com/weble/linkedhouse/customer/controller/CustomerController.java, src/main/java/com/weble/linkedhouse/customer/dtos/ProfileDto.java, src/main/java/com/weble/linkedhouse/customer/dtos/response/LoginResponse.java, src/main/java/com/weble/linkedhouse/customer/service/CustomerService.java, src/main/java/com/weble/linkedhouse/exception/controller/ExceptionControllerAdvise.java, src/main/java/com/weble/linkedhouse/house/service/HouseHostService.java, src/main/java/com/weble/linkedhouse/security/jwt/JwtAuthenticationFilter.java, src/main/java/com/weble/linkedhouse/security/jwt/JwtTokenProvider.java, src/main/java/com/weble/linkedhouse/util/CookieUtil.java, src/main/java/com/weble/linkedhouse/util/CreateFile.java, src/main/java/com/weble/linkedhouse/util/storage/NaverProperties.java, src/main/java/com/weble/linkedhouse/util/storage/NcpObjectStorage.java, src/main/java/com/weble/linkedhouse/util/storage/ObjectStorage.java, src/main/resources/application.yml, src/test/java/com/weble/linkedhouse/customer/service/CustomerServiceTest.java, src/test/java/com/weble/linkedhouse/house/service/HouseServiceTest.java, src/test/resources/application.yml
=> Object Storage 관련 추가 및 설정

src/main/java/com/weble/linkedhouse/house/controller/HouseCustomerController.java, src/main/java/com/weble/linkedhouse/house/dto/FilterKeyword.java, src/main/resources/application.yml
- SearchKeyword 에 대해 ModelAttribute Annotation 적용
- 오타 수정
=> fix : House Controller 에서 ModelAttribute 를 처리하도록 변경

src/main/java/com/weble/linkedhouse/house/controller/HouseHostController.java, src/main/java/com/weble/linkedhouse/house/dto/response/HouseResponseDto.java, src/main/java/com/weble/linkedhouse/house/service/HouseHostService.java
- DTO 관련 누락 부분 추가 (minCapacity, bed, bathRoom, room)
- Reservation Type에 관한 Upgrade API 작성
=> 프론트 작업중 House 관련 수정 및 추가 분 작성

src/main/java/com/weble/linkedhouse/house/controller/HouseCustomerController.java, src/main/java/com/weble/linkedhouse/house/dto/FilterKeyword.java, src/main/java/com/weble/linkedhouse/house/repository/HouseRepositoryCustom.java, src/main/java/com/weble/linkedhouse/house/repository/HouseRepositoryCustomImpl.java, src/main/java/com/weble/linkedhouse/house/service/HouseCustomerService.java, src/main/java/com/weble/linkedhouse/security/SecurityConfig.java, src/test/java/com/weble/linkedhouse/house/service/HouseServiceTest.java
- SecurityConfig 에서 setAllowedOrigin 을 setAllowedOriginPatterns 로 수정
- setAllowCredentials 추가
- findAllHouse를 모두 RequestParam으로 수정, FilterKeyword 를 String으로 수정
=>  feat : HouseCustomerController CORS 문제 수정, 파라미터 수정 #160 

src/main/java/com/weble/linkedhouse/house/controller/HouseCustomerController.java, src/main/java/com/weble/linkedhouse/house/dto/FilterKeyword.java, src/main/java/com/weble/linkedhouse/house/repository/HouseRepositoryCustom.java, src/main/java/com/weble/linkedhouse/house/repository/HouseRepositoryCustomImpl.java, src/main/java/com/weble/linkedhouse/house/service/HouseCustomerService.java, src/main/java/com/weble/linkedhouse/security/SecurityConfig.java, src/test/java/com/weble/linkedhouse/house/service/HouseServiceTest.java
* fix : 파라미터 수정, setAllowedOriginPatterns 도입
=>  feat : HouseCustomerController CORS 문제 수정, 파라미터 수정 #160
